name: Run Data Sync On Schedule

on:
  schedule:
    - cron: '0 0 * * *'


jobs:
  sync_file:
    name: sync file
    secrets: inherit
    uses: ./.github/workflows/run_data_sync.yml
    with:
        run_type: garmin_cn
