name: Run Data Sync When Push

on:
  push:
    branches:
      - master
    paths:
      - scripts/garmin_sync.py

jobs:
  sync_file:
    name: sync file
    secrets: inherit
    uses: ./.github/workflows/run_data_sync.yml
    with:
        run_type: "garmin_cn"
